# Generated by Django 5.2.1 on 2025-05-17 07:57

import django.db.models.deletion
import stadium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stadium", "0016_remove_ticket_order_alter_ticket_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "actors",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_sports", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "genres",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "teams",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration", models.IntegerField()),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=stadium.models.event_image_file_path
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, related_name="event_actors", to="show.actor"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="event_genres", to="show.genre"
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True, related_name="event_teams", to="show.team"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "events",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_time", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="show.event",
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        related_name="sections", to="stadium.section"
                    ),
                ),
                (
                    "sportarena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stadium.sportarena",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "eventsessions",
                "ordering": ["-show_time"],
            },
        ),
    ]
