# Generated by Django 5.2.1 on 2025-05-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stadium", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsession",
            name="section",
        ),
        migrations.AddField(
            model_name="eventsession",
            name="section",
            field=models.ManyToManyField(related_name="sections", to="stadium.section"),
        ),
    ]
