# Generated by Django 5.2.1 on 2025-05-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stadium", "0003_remove_eventsession_section_eventsession_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="teams",
            field=models.ManyToManyField(related_name="event_teams", to="stadium.team"),
        ),
    ]
