# Generated by Django 5.2.1 on 2025-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stadium", "0004_alter_event_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="actors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="event_actors", to="stadium.actor"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="teams",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="event_teams", to="stadium.team"
            ),
        ),
    ]
