# Generated by Django 5.2.1 on 2025-05-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stadium", "0008_alter_eventsession_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="sportarena",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="stadium.sportarena",
            ),
            preserve_default=False,
        ),
    ]
