# Generated by Django 5.2.1 on 2025-05-10 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stadium", "0009_event_sportarena"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["section", "row", "seat"]},
        ),
        migrations.AlterField(
            model_name="ticket",
            name="event_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_eventsession",
                to="stadium.eventsession",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="stadium.order",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_order",
                to="stadium.section",
            ),
        ),
    ]
