# Generated by Django 5.2.1 on 2025-05-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stadium", "0011_alter_ticket_options_alter_ticket_event_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="sportarena",
        ),
        migrations.AddField(
            model_name="eventsession",
            name="sportarena",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="stadium.sportarena",
            ),
            preserve_default=False,
        ),
    ]
