# Generated by Django 5.2.1 on 2025-05-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stadium", "0013_sportarena_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sportarena",
            name="section",
        ),
        migrations.AddField(
            model_name="section",
            name="sportarena",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="stadium.sportarena",
            ),
            preserve_default=False,
        ),
    ]
