# Generated by Django 5.2.1 on 2025-05-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stadium", "0014_remove_sportarena_section_section_sportarena"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["sportarena", "name"],
                "verbose_name_plural": "sections",
            },
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("sportarena", "name")},
        ),
    ]
