# Generated by Django 5.2.1 on 2025-05-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stadium", "0015_alter_section_options_alter_section_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="order",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="event_session",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="section",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
