# Generated by Django 5.2.1 on 2025-05-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_alter_ticket_event_session"),
        ("stadium", "0016_remove_ticket_order_alter_ticket_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="actors",
        ),
        migrations.RemoveField(
            model_name="event",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="event",
            name="teams",
        ),
        migrations.RemoveField(
            model_name="eventsession",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventsession",
            name="sections",
        ),
        migrations.RemoveField(
            model_name="eventsession",
            name="sportarena",
        ),
        migrations.DeleteModel(
            name="Actor",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventSession",
        ),
    ]
