# Generated by Django 5.2.1 on 2025-05-17 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="event_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_event_sessions",
                to="show.eventsession",
            ),
        ),
    ]
